name: plate_pal
description: PlatePal is a mobile application that allows users to organize their recipes effectively.

publish_to: 'none' 
version: 1.0.2+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.0
  freezed_annotation: ^2.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_serializable: ^6.2.0
  dio: ^4.0.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  file: ^6.1.4
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  cloud_firestore: ^4.8.0
  logger: ^1.3.0
  firebase_storage: ^11.2.2
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  firebase_auth: ^4.6.2
  sign_in_button: ^3.2.0
  file_picker: ^5.3.1
  restart_app: ^1.2.0
  shared_preferences: ^2.1.1
  flutter_i18n: ^0.33.0
  google_mlkit_text_recognition: 0.7.0
  dart_openai: 2.0.0
  beamer: ^1.5.5
  flutter_reorderable_list: ^1.3.1
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.11
  flutter_spinkit: ^5.1.0
  open_file: ^3.3.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.2
  flutter_lints: ^1.0.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  analyzer: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/platepal.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/images/
    - assets/i18n/
  uses-material-design: true
