// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'filter_model.freezed.dart';

@freezed
class FilterModel with _$FilterModel {
  const factory FilterModel(
      {required bool vegan,
      required bool vegetarisch,
      required bool glutenfrei}) = _FilterModel;
}
