// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:plate_pal/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: '1:163671621768:web:2d6cbad11c8d75ce825f3d',
    messagingSenderId: '163671621768',
    projectId: 'platepal-manz',
    authDomain: 'platepal-manz.firebaseapp.com',
    databaseURL:
        'https://platepal-manz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-manz.appspot.com',
    measurementId: 'G-EX7L2YB6D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApiKey,
    appId: '1:163671621768:android:371b6fd958f86044825f3d',
    messagingSenderId: '163671621768',
    projectId: 'platepal-manz',
    databaseURL:
        'https://platepal-manz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-manz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIOSApiKey,
    appId: '1:163671621768:ios:e06e9f7c35dee806825f3d',
    messagingSenderId: '163671621768',
    projectId: 'platepal-manz',
    databaseURL:
        'https://platepal-manz-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-manz.appspot.com',
    iosClientId:
        '163671621768-0s1hfsik6gm1gr5j3b0di8p0801gjh36.apps.googleusercontent.com',
    iosBundleId: 'com.platePal.ios',
  );
}
