// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:plate_pal/secrets.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: '1:296458758683:web:a764aec916b8abf0ebe6be',
    messagingSenderId: '296458758683',
    projectId: 'platepal-60ea4',
    authDomain: 'platepal-60ea4.firebaseapp.com',
    databaseURL:
        'https://platepal-60ea4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-60ea4.appspot.com',
    measurementId: 'G-M7VCFE76P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApiKey,
    appId: '1:296458758683:android:e2d0fe6ad307e616ebe6be',
    messagingSenderId: '296458758683',
    projectId: 'platepal-60ea4',
    databaseURL:
        'https://platepal-60ea4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-60ea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIOSApiKey,
    appId: '1:296458758683:ios:e309c04f1f1a0c55ebe6be',
    messagingSenderId: '296458758683',
    projectId: 'platepal-60ea4',
    databaseURL:
        'https://platepal-60ea4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'platepal-60ea4.appspot.com',
    iosClientId:
        '296458758683-7f9otil1hhrf54srpmfojmoirao5p032.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
