// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'gruppe_model.freezed.dart';

@freezed
class GruppeModel with _$GruppeModel {
  const factory GruppeModel({
    required List<Member> members,
  }) = _GruppeModel;
}

@freezed
class Member with _$Member {
  const factory Member(
      {required String name,
      required String id,
      required String image,
      required int ammount}) = _Member;
}
